// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ONNXML.Model
{
    public class ModelInput
    {
        [ColumnName("ReviewText"), LoadColumn(0)]
        public string ReviewText { get; set; }


        [ColumnName("Sentiment"), LoadColumn(1)]
        public string Sentiment { get; set; }


    }
}
